#include <unordered_map>

namespace utils {
  const int*  const C_CAR_PTR     = (int*)  0x009BA088;
  const int*  const CARS_ADDR_PTR = (int*)  0x009B09D8;
  const int*  const OPT_ADDR_PRT  = (int*)  0x0091CF90;

  std::unordered_map<std::string, const char*> CAR_TABLE = {
    {"997S", "Porsche 911 Carrera S"},
    {"IS300", "Lexus IS 300"},
    {"PUNTO", "Fiat Grande Punto"},
    {"COBALTSS", "Chevrolet Cobalt SS"},
    {"GTI", "Volkswagen Golf GTI"},
    {"TT", "Audi TT 3.2 Quattro"},
    {"A3", "Audi A3 3.2 Quattro"},
    {"ECLIPSEGT", "Mitsubishi Eclipse GT"},
    {"A4", "Audi A4 3.2 FSI Quattro"},
    {"SUPRA", "Toyota Supra RZ"},
    {"CLIO", "Renault Clio V6 RS"},
    {"RX8", "Mazda RX-8"},
    {"RX7", "Mazda RX-7"},
    {"CTS", "Cadillac CTS"},
    {"MUSTANGGT", " Ford Mustang GT"},
    {"LANCEREVO8", "Mitsubishi Lancer Evolution VIII"},
    {"SL500", "Mercedes-Benz SL 500"},
    {"GTO", "Pontiac GTO"},
    {"MONARO", "Vauxhall Monaro VXR"},
    {"CAYMANS", "Porsche Cayman S"},
    {"IMPREZAWRX", "Subaru Impreza WRX STi"},
    {"CLK500", "Mercedes-Benz CLK 500"},
    {"ELISE", "Lotus Elise 111R"},
    {"DB9", "Aston Martin DB9"},
    {"VIPER", "Dodge Viper SRT-10"},
    {"GALLARDO", "Lamborghini Gallardo"},
    {"911TURBO", "Porsche 911 Turbo S"},
    {"CORVETTE", "Chevrolet Corvette"},
    {"MURCIELAGO", "Lamborghini Murciélago"},
    {"FORDGT", " Ford GT"},
    {"SLR", "Mercedes-Benz SLR McLaren"},
    {"CARRERAGT", "Porsche Carrera GT"},
    {"BMWM3GTRE46", "BMW M3 GTR"},
    {"22GTR35", "Nissan GT-R T-Spec"},
    {"300SLR", "Mercedes-Benz 300 SLR"},
    {"350Z", "Nissan 350Z"},
    {"360MODENA", "Ferrari 360 Modena"},
    {"512TR", "Ferrari 512 Testarossa"},
    {"850R", "Volvo 850R Estate"},
    {"911GT2", "Porsche 911(996) GT2"},
    {"911GT2993RWB", "Porsche 911 (993) GT2 RWB"},
    {"930TURBO", "Porsche 930 Turbo"},
    {"EB110SS", "Bugatti EB110 Supersport"},
    {"C8VETTE", "Chevrolet Corvette (C8)"},
    {"CAMARO", "Chevrolet Camaro SS 396"},
    {"CHALLENGER71", "Dodge Challenger R/T 440"},
    {"CHARGER06", "Dodge Charger SRT8"},
    {"CHARGER69", "1969 Dodge Charger R/T"},
    {"COMMODORE96", "1996 HSV GTS-R"},
    {"COROLLAE88", "Toyota Corolla GT-S (AE88)"},
    {"CORVETTEC6R", "Chevrolet Corvette C6.R"},
    {"DELTA", "Lancia Delta HF Integrale Evoluzione II"},
    {"ESTILO", "Honda Civic Si"},
    {"EVORA", "Lotus Evora"},
    {"F40", "Ferrari F40"},
    {"FORDGTX1", "Ford GTX1"},
    {"FXXKEVO", "Ferrari FXX-K Evo"},
    {"GALLARDO10VB", "Lamborghini Gallardo LP550-2"},
    {"GRYARIS", "Toyota GR Yaris (XP210)"},
    {"GTI2016", "Volkswagen Golf GTI Clubsport (MkVII)"},
    {"GTO65", "Pontiac GTO '65"},
    {"IMPALASS", "Chevrolet Impala SS"},
    {"IMPREZA", "Subaru Impreza 2.5 RS (GDE)"},
    {"IMPREZA22B", "Subaru Impreza 22B-STi (GC8)"},
    {"INTEGRA00", "Honda Integra Type R (DC2)"},
    {"ISF", "Lexus IS F (USE20)"},
    {"LANCEREVO3", "Mitsubishi Lancer GSR Evolution III"},
    {"LANCEREVO5", "Mitsubishi Lancer Evolution V GSR"},
    {"MAZDA3SPORT", "Mazda 3 Sport"},
    {"MCLARENF1", "McLaren F1"},
    {"NEON", "1999 Dodge Neon"},
    {"NEWBEETLE", "Volkswagen New Beetle Turbo S"},
    {"NSXNA1", "Honda NSX (NA1)"},
    {"RACINGPUMA", "Ford Racing Puma"},
    {"RS5", "Audi RS5"},
    {"RUFRT12", "RUF RT 12 S"},
    {"RX7FC", "Mazda Savanna RX-7 (FC3S)"},
    {"RX8SPEEDT", "Mazda RX-8 Speed T"},
    {"S2000", "Honda S2000(AP1)"},
    {"S28103", "Saleen S281 '03"},
    {"SILVIAS15", "Nissan Silvia (S15)"},
    {"SKYLINE33R", "Nissan Skyline GT-R V-Spec (BCNR33)"},
    {"SKYLINER32", "Nissan Skyline GT-R (BNR32)"},
    {"SKYLINEZT", "Nissan Skyline GT-R Nismo Z-Tune (BNR34)"},
    {"SL65", "Mercedes-Benz SL 65 AMG"},
    {"SUPRAGA70", "Toyota Supra 2.0GT Twin Turbo (GA70)"},
    {"TIBURON", "Hyundai Tiburon GT"},
    {"TOMKAR34", "Tommy Kaira R (R34)"},
    {"VANQUISH01", "Aston Martin V12 Vanquish"},
    {"WRXSTI15", "2015 Subaru WRX STI"},
    {"WRXSTI2006", "2006 Subaru WRX STI"},
	{"ZL1MKVI", "Chevrolet Camaro ZL1 (Mk VI)"},
	{"ME412", "Chrysler ME Four-Twelve"},
	{"ZPROTO21", "Nissan Z Proto"},
	{"911GT1", "Porsche 911 GT1 Straßenversion"},
	{"BMW1M", "BMW 1 Series M Coupe (E82)"},
	{"BMWM3", "BMW M3(E46)"},
	{"BMWM3GTR", "BMW M3 GTR Strassenversion(E46)"},
	{"CCXR", "Koenigsegg CCXR Edition"},
	{"F50", "Ferrari F50"},
  };
}
